language: python

python:
  - "3.5"

#services:
#  - mysql

env:
  - DJANGO=1.11.7

install:
  - pip3 install -q django==$DJANGO
  - pip3 install -q djangorestframework

script:
  - python3 manage.py test