language: python

python:
  - "3.5"

#services:
#  - mysql

env:
  - DJANGO=1.11.7

install:
  - pip3 install -q django==$DJANGO
  - pip3 install -q djangorestframework
  - pip3 install djangorestframework
  - pip3 install coveralls
  - pip3 install drfdocs

script:
  - python3 manage.py test 
  - coverage run --source=python3 manage.py test
  
after_success:
  - coveralls
 
