language: python
python: 
  - "3.5"

#services:
#  - mysql

env:
  - DJANGO=1.11.7
  
before_install:
  - export PYTHONPATH=$HOME/builds/MatiasLoiseau/api-rest/
  
install:
  - pip3 install -q django==$DJANGO
  - pip3 install -q djangorestframework
  - pip install coveralls

script:
  - python3 manage.py test 
  - coverage run --source=tp,usuario,cuenta,categoria,movimiento manage.py test
  
after_success:
  - coveralls
 
