language: python

python:
  - "2.7"

#services:
#  - mysql

env:
  - DJANGO=1.11.7

install:
  - pip install -q django==$DJANGO
  - pip install -q djangorestframework

script:
  - python3 manage.py test