# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ('nombreCuenta',)},
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='nombre',
            new_name='nombreCuenta',
        ),
    ]
