# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0002_auto_20171122_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('cuentas', models.ManyToManyField(to='cuentas.Cuenta')),
            ],
            options={
                'ordering': ('username',),
            },
        ),
    ]
